services:
  geralt:
    build: .
    container_name: geralt_bot
    command: python3 main.py
    restart: unless-stopped
    volumes:
      - ./database.db:/app/database.db
      - ./Logging/logs:/app/Logging/logs
      - ./download_youtube:/app/download_youtube
      - ./tmp:/app/tmp
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celery_conf worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"