version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celery_conf worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
